package jdbox.content.bytestores;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.Arrays;

public abstract class AutoGeneratedContentByteStore implements ByteStore {

    @Override
    public int read(ByteBuffer buffer, long offset, int count) throws IOException {
        String content = getContent();
        buffer.put(Arrays.copyOfRange(content.getBytes(), (int) offset, (int) (offset + count)));
        return (int) Math.min(count, content.length() - offset);
    }

    @Override
    public void close() throws IOException {
    }

    @Override
    public int write(ByteBuffer buffer, long offset, int count) throws IOException {
        throw new UnsupportedOperationException("write is not supported");
    }

    @Override
    public void truncate(long offset) throws IOException {
        throw new UnsupportedOperationException("truncate is not supported");
    }

    protected abstract String getContent();
}
