package jdbox.content;

import com.google.inject.Inject;
import jdbox.models.File;
import jdbox.uploader.Uploader;

class UploadStatusOpenedFile extends AutoGeneratedContentByteStore {

    private final Uploader uploader;

    UploadStatusOpenedFile(Uploader uploader) {
        this.uploader = uploader;
    }

    @Override
    protected String getContent() {
        return getContent(uploader);
    }

    public static String getContent(Uploader uploader) {
        return uploader.getCurrentStatus().asString();
    }
}

class UploadStatusOpenedFileFactory implements ByteStoreFactory {

    private final Uploader uploader;

    @Inject
    UploadStatusOpenedFileFactory(Uploader uploader) {
        this.uploader = uploader;
    }

    @Override
    public long getSize(File file) {
        return UploadStatusOpenedFile.getContent(uploader).length();
    }

    @Override
    public ByteStore create(File file) {
        return new UploadStatusOpenedFile(uploader);
    }
}
