package jdbox.content.filetypes;

import jdbox.content.bytestores.AutoGeneratedContentByteStore;
import jdbox.uploader.Uploader;

class UploadStatusOpenedFile extends AutoGeneratedContentByteStore {

    private final Uploader uploader;

    UploadStatusOpenedFile(Uploader uploader) {
        this.uploader = uploader;
    }

    @Override
    protected String getContent() {
        return getContent(uploader);
    }

    public static String getContent(Uploader uploader) {
        return uploader.getCurrentStatus().asString();
    }
}

