package jdbox.openedfiles;

import jdbox.models.File;

class NonDownloadableOpenedFile extends AutoGeneratedContentByteStore {

    @SuppressWarnings("FieldCanBeLocal")
    private static String contentTemplate =
            "[Desktop Entry]\n" +
                    "Version=1.0\n" +
                    "Encoding=UTF-8\n" +
                    "Type=Link\n" +
                    "Name={name}\n" +
                    "URL={href}\n" +
                    "Icon=text-html\n";

    private final File file;

    NonDownloadableOpenedFile(File file) {
        this.file = file;
    }

    @Override
    protected String getContent() {
        return getContent(file);
    }

    public static String getContent(File file) {
        return contentTemplate
                .replace("{name}", file.getName())
                .replace("{href}", file.getAlternateLink());
    }
}

class NonDownloadableOpenedFileFactory implements ByteStoreFactory {

    @Override
    public long getSize(File file) {
        return NonDownloadableOpenedFile.getContent(file).length();
    }

    @Override
    public NonDownloadableOpenedFile create(File file) {
        return new NonDownloadableOpenedFile(file);
    }
}
